# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GovTest < Formula
  desc ""
  homepage "https://github.com/dev-ujin/gov-test"
  version "1.0.5"

  on_macos do
    on_intel do
      url "https://github.com/dev-ujin/gov-test/releases/download/v1.0.5/gov-test_Darwin_x86_64.tar.gz"
      sha256 "5fdbf6de43322c0d2ccb69546194fed842b8b64df55fc971a79bc2d22f45c2f1"

      def install
        bin.install "gov-test"
      end
    end
    on_arm do
      url "https://github.com/dev-ujin/gov-test/releases/download/v1.0.5/gov-test_Darwin_arm64.tar.gz"
      sha256 "41d7b90e73abf67e6495384986fa3296d991b07caec33d776a197bbd671867e9"

      def install
        bin.install "gov-test"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dev-ujin/gov-test/releases/download/v1.0.5/gov-test_Linux_x86_64.tar.gz"
        sha256 "6ecf707ebae4e31fb49a5f381dfca81bc54f076e4cb7fb47e14397971a63ab32"

        def install
          bin.install "gov-test"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dev-ujin/gov-test/releases/download/v1.0.5/gov-test_Linux_arm64.tar.gz"
        sha256 "e90821d4f09c29bf06e7dac6e241cc32edcdab3bf2a7ed5090e27ce828f3106b"

        def install
          bin.install "gov-test"
        end
      end
    end
  end
end
